name: Tests

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Log current directory
          run: pwd  # Print de huidige directory

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r Program/requirements.txt
          working-directory: Program  # Voer het uit in de Program map

        - name: Test with pytest
          run: pytest
          working-directory: Program  # Voer het uit in de Program map
